version: "3.1"

services:
  webserver:
    image: nginx:alpine
    working_dir: /application
    volumes:
        - ./dist/my-app:/application
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"